Description: |
  Create an EC2 development instance with vim, git, tmux, mosh and
  docker installed.

Parameters:

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: |
      Name of an existing EC2 KeyPair to enable SSH access to the
      instance

  InstanceType:
    Type: String
    Description: |
      EC2 instance type to use
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large

  CidrIp:
    Type: String
    Description: |
      Specify the IPv4 CIDR range for ingress (SSH/Mosh) allowed by
      the security group added to the EC2 instance
    Default: "0.0.0.0/0"
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[0-9]))$
    ConstraintDescription: |
      must be an valid IPv4 CIDR range of the form x.x.x.x/x

  CidrIpv6:
    Type: String
    Description: |
      Specify the IPv6 CIDR range for ingress (SSH/Mosh) allowed by
      the security group added to the EC2 instance
    Default: "::/0"

  CfnBootstrapUrl:
    Type: String
    Description: URL to aws-cfn-boostrap to install
    Default: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

Mappings:

  # These are the latest Ubuntu Server 18.04 LTS (HVM) as of 2018-09

  AWSRegionToAMI:
    eu-west-1:
      AMI: ami-00035f41c82244dab
    eu-central-1:
      AMI: ami-0bdf93799014acdc4

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH/Mosh access
      SecurityGroupIngress:
        - Description: SSH
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref CidrIp
        - Description: Mosh
          IpProtocol: UDP
          FromPort: 60000
          ToPort: 61000
          CidrIp: !Ref CidrIp
        - Description: SSH
          IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIpv6: !Ref CidrIpv6
        - Description: Mosh
          IpProtocol: UDP
          FromPort: 60000
          ToPort: 61000
          CidrIpv6: !Ref CidrIpv6

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ AWSRegionToAMI, !Ref "AWS::Region", AMI ]
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: !Ref KeyName
      UserData:
        # install aws-cfn-boostrap
        # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html
        Fn::Base64: !Sub |
          #!bin/bash -xe
          apt-get update
          apt-get -y install python-pip

          pip install "${CfnBootstrapUrl}"

          cfn-init --resource EC2Instance \
                   --stack "${AWS::StackName}" \
                   --region "${AWS::Region}" -v

          cfn-signal --resource EC2Instance \
                     --stack "${AWS::StackName}"
                     --region "${AWS::Region}" -e $?
    Metadata:
      AWS::CloudFormation::Init:
        # see https://garbe.io/blog/2017/01/20/install-docker-1.13-on-aws-via-cloudformation/
        # for example on how latest version of docker can be installed
        config:
          packages:
            apt:
              git: []
              mosh: []
              tmux: []
              vim: []
